### ISSUE TITLE
Look & Feel stili Regione Lombardia

### ISSUE THREAD

**Issue by strawberry-code** [strawberry-code/io-app#11]
[Story Clubohouse](https://app.clubhouse.io/pwc-ssi/story/368/look-and-feel-regione).

- [x] cambio colori principali dell'app da blu a verde secondo stili pdf

- [x] cambio logo app android

- [x] cambio logo app ios (@strawberry-code )

- [x] cambio splash screen android

- [x] cambio splash screen ios (@strawberry-code )

- [x] nascondere i bottom tabs di io-app

**Comment by strawberry-code** [comment]
Siamo ad un buon punto, ma teniamolo ancora aperto in attesa di un feedback da parte di @andreataglia

**Comment by strawberry-code** [comment]
@despotes https://app.clubhouse.io/pwc-ssi/story/368/look-and-feel-regione

Manca solo il logo di regione lombardia e rifare lo splashscreen che è blu, va messo in verde (proviamo a metterlo gradiente come fanno loro, se complicato, mettiamolo colore omogeneo).

**Comment by despotes** [comment]
@strawberry-code La parte della sfondo l'ho fatta nella versione Android, cercherò di mettere logo e togliere quelli già presenti con dei placeholder intanto.
Nella versione iOS, non ho XCode e per la modifica dello SplashScreen, serve quello.

**Comment by strawberry-code** [comment]
Risolto
