### ISSUE TITLE
Scaffolding Viste e Navigations per Wallet ERC20

### ISSUE THREAD

**Issue by strawberry-code** [strawberry-code/io-app#12]
Implementare viste e navigation per il sistema ERC20 Wallet, dopodichè chiudere questa story e crearne un'altra per l'implementazione delle logiche.

- [x] fase 1

- [x] fase 2

## Fase 1
La prima fase consiste nel realizzare tre nuove viste e collegarle ai relativi buttons, come nell'immagine seguente

![Mock Wallet 1](https://user-images.githubusercontent.com/18684103/100087528-2ac85c00-2e4f-11eb-8c3f-11a37bb8525d.png)

I requisiti sono:

- [x]  Le nuove viste dovranno essere "vuote", ma dovranno implementare la vista di base standard che ci sono già (per esempio il button di back e i title della vista, si possono copiare dalle altre viste (ad esempio da quella di ssi) e poi togliere tutte le componenti che non ci servono

- [x]  Il tasto back button deve funzionare: questo funziona già se copiato dalla componente che già si trova nelle altre viste di pagopa

- [x]  Ogni vista dovrà avere un file dedicato eciascuna di queste viste dovrà essere configurata come fatto con le altre (cercare SSI_NAVIGATOR, SSI_HOME, gli stores e così via) e saranno:

- [x] **balanceAndTransaction.tsx**

- [x] **walletSend.tsx**

- [x] **walletReceive.tsx**

## Fase 2

Come da immagine seguente:

- [ ] Vista **Balance & Transaction**
- [ ] Vista **Send**
- [ ] Vista **Receive**

![Mock Wallet](https://user-images.githubusercontent.com/18684103/100205866-f19ef300-2f05-11eb-8b0e-4bd22c3983a7.png)

**Comment by despotes** [comment]
Intanto ho creato le View Vuote e le ho collegate ai Bottoni:
1. In basso a sinistra Ho messo la View di Wallet Send
2. In basso a destra ho messo la View di Wallet Receive
3. Ho creato la View Balance e Transaction, ma non l'ho collegato al bottone in alto a destra perché non volevo togliere il collegamento allo ScanQR Code, al riguardo mi farai sapere.

**Comment by strawberry-code** [comment]
Ottimo lavoro! Appena torno lo vediamo.

Ti dico subito che per il QR non serve mantenere l'aggancio alla vista QR, perché abbiamo giù un button QR rettangolare che si trova sotto ai quattro buttons rotondi.

Quindi possiamo procedere scollegando il link del button rotondo che sta in alto a destra e metterci di quello di una nuova vista.

Ottimo lavoro! 👏

**Comment by strawberry-code** [comment]
Concludiamo fase 1 con la a1246cc430aa9bb3e882b55441c11b40131a2ad8

**Comment by strawberry-code** [comment]
Nei buttons send e receive ho detto *chiamate ad API*, non sarà così, quando implementeremo le logiche lo vedremo.

**Comment by strawberry-code** [comment]
Mi pare finito, a parte qualche accorgimento cui dettagli possono essere descritti su nuovi issues @V0nMis3s

**Comment by V0nMis3s** [comment]
Concordo!
