### ISSUE TITLE
Problema con primo avvio del modulo di scansione QR

### ISSUE THREAD

**Issue by strawberry-code** [strawberry-code/io-app#2]
Il modulo di scansione QR in SSI non parte subito, bisogna andare indietro di una vista e poi ritornare nuovamente sulla scansione QR.

Lo fa solo la prima volta che parte l'app e poi rimane "caldo".

![qr-issue](https://user-images.githubusercontent.com/18684103/95992447-3f680c00-0e2e-11eb-8082-877e16fbd754.gif)

**Comment by strawberry-code** [comment]
Prova! :D

**Comment by strawberry-code** [comment]
Prova prova! D:

**Comment by david-speakslow** [comment]
prova

**Comment by strawberry-code** [comment]
mudò

**Comment by strawberry-code** [comment]
olè! olè! 👯

**Comment by strawberry-code** [comment]
we we

**Comment by david-speakslow** [comment]
prova2

**Comment by strawberry-code** [comment]
il commit non l'ha puntato

**Comment by strawberry-code** [comment]
Risolto con 987b6f5baf9c5bca4d61e6aa0a4f85019393c092
