### ISSUE TITLE
Non ricevo dalla fetch request dopo aver scansionato QR Code.

### ISSUE THREAD

**Issue by despotes** [strawberry-code/io-app#8]
**Descrizione problema**
Non ricevo alcun data dalla fetch request dopo aver scansionato il Qr code

**Per riprodurre*
1. Andare sul sito https://ssi-aria-dashboard.netlify.app/vcreader
2. Andare Sezione SSI della App  e scansionare per la shareQR 

**Expected behavior**
Dovrebbe ritornare del data dalla funzione VCStore.getVCs()

**Screenshots**
![Immagine 2020-11-19 164832](https://user-images.githubusercontent.com/39811448/99689201-ff2c2700-2a86-11eb-9c3d-e20f2eb2ea80.jpg)
Faccio la lettura del QR.

**Smartphone (please complete the following information):**
 - Device: Samsung A6
 - OS: Android 10

**Additional context**
Il motivo può essere perché non ho alcuna Credenziale Verificata sul profilo?

**Comment by strawberry-code** [comment]
Si, credo che il problema possa essere che non abbiamo VC.

Pare che sia causato da un cambio di API venuto male lato server, abbiamo riscontrato il problema anche noi. 

Ci stiamo lavorando su, grazie per le informazioni super dettagliate! ;) Ottimo! 🎉

Aggiornerò l'issue appena sappiamo qualcosa.

**Comment by strawberry-code** [comment]
Risolto
